authors:
  dgraus:
    name: David Graus
    description: Lab Manager 
    avatar: https://avatars.githubusercontent.com/u/894054?v=4
    url: https://graus.nu
  mmarx:
    name: Maarten Marx
    description: Lab Director
    avatar: https://avatars.githubusercontent.com/u/3773808?s=96&v=4
  jkamps:
    name: Jaap Kamps
    description: Lab Director
    avatar: https://avatars.githubusercontent.com/u/5208951?s=64&v=4
  mlarooij:
    name: Maik Larooij
    description: PhD Student
    avatar: https://avatars.githubusercontent.com/u/54892350?v=4
  dreijnaers:
    name: Damiaan Reijnaers
    description: PhD Student
    avatar: https://avatars.githubusercontent.com/u/10456122?v=4
